---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.23
  amd64: ghcr.io/home-assistant/amd64-base:3.23
labels:
  project: https://github.com/rommapp/romm
  maintainer: bluemaex <homeassistant@blmx.de>
  org.opencontainers.image.authors: rigerc
  org.opencontainers.image.licenses: MIT License
  org.opencontainers.image.title: 'Home Assistant Unofficial Add-on: romm'
  org.opencontainers.image.url: https://github.com/rigerc/ha-apps
  org.opencontainers.image.source: https://github.com/rommapp/romm
  org.opencontainers.image.documentation: https://github.com/rigerc/ha-apps/romm/README.md
