# ==============================================================================
# build.yaml — Home Assistant Add-on build configuration
#
# Specifies the base images used for each target architecture.
# ==============================================================================

# Kapowarr is a Python application (Flask) - use Python base image
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.21
  amd64: ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.21

# OCI image labels
labels:
  # Upstream project URL for version tracking
  project: https://github.com/Casvt/Kapowarr

  maintainer: rigerc
  org.opencontainers.image.authors: rigerc
  org.opencontainers.image.licenses: GPL-3.0
  org.opencontainers.image.title: "Home Assistant Unofficial Add-on: Kapowarr"
  org.opencontainers.image.description: "Comic book library manager with automated downloading, renaming, and conversion"
  org.opencontainers.image.source: https://github.com/rigerc/ha-apps/kapowarr
  org.opencontainers.image.url: https://github.com/rigerc/ha-apps
  org.opencontainers.image.documentation: https://github.com/rigerc/ha-apps/kapowarr/DOCS.md
  io.hass.upstream.image: mrcas/kapowarr
